name: Stream_checker-BD

on:
  schedule:
    - cron: "0 */8 * * *" # Every 8 hours
  workflow_dispatch:

jobs:
  check-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stream processor
        run: python BugsfreeStreams/process_streams-BD.py

      - name: Show logs
        run: cat /tmp/*.log || echo "No logs found"

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add BugsfreeStreams/
          git diff --staged --quiet || git commit -m "Update stream links"
          git push origin main || echo "No changes to push"
