name: Stream Checker

on:
  schedule:
    - cron: "0 */8 * * *" # Every 8 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  check-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run stream processor
        run: python process_streams.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add BugsfreeStreams/
          git commit -m "Update stream links" || echo "No changes to commit"
          git push origin main
